/* =========================================================
   custom-content.js — GENERATED by tools/editor. Do not hand-edit;
   your changes will be overwritten the next time you click Save
   in the content editor. Loads after data.js, so it can add new
   cards/resources/items/locations/stations/skills, or override a
   field on an existing one (re-declared in full below).

   Nothing in the base data.js or sprites.js is ever modified by
   the editor; every change from the editor lands here (or in
   custom-sprites.js) instead.
   ========================================================= */
(function (G) {
  'use strict';

  /* ---- Resources ---- */
  Object.assign(G.RESOURCES, {
  "stone": {
    "name": "Stone",
    "tint": "stone",
    "worth": 0.25,
    "wt": 1
  },
  "flint": {
    "name": "Flint",
    "wt": 0.5,
    "tint": "stone",
    "worth": 0.05
  },
  "flax": {
    "name": "Flax",
    "wt": 0.05,
    "tint": "plant",
    "worth": 0.5
  },
  "berries": {
    "name": "Red Berries",
    "wt": 0.1,
    "tint": "blood",
    "worth": 2
  },
  "feathers": {
    "name": "Chicken Feathers",
    "wt": 0.05,
    "tint": "cloth",
    "worth": 0.1
  },
  "bone": {
    "name": "Bones",
    "wt": 0.1,
    "tint": "bone",
    "worth": 3
  },
  "berrySeed": {
    "name": "Berry Seeds",
    "wt": 0.05,
    "tint": "plant",
    "worth": 2.5
  },
  "animalFat": {
    "name": "Animal Fat",
    "wt": 0.1,
    "tint": "cloth",
    "worth": 0.5
  },
  "pondweed": {
    "name": "Pondweed",
    "wt": 0.05,
    "tint": "plant",
    "worth": 1
  },
  "smoothStone": {
    "name": "Smooth Stone",
    "wt": 0.25,
    "tint": "stone",
    "worth": 1
  },
  "bluegill": {
    "name": "Bluegill",
    "wt": 0.25,
    "tint": "range",
    "worth": 2
  },
  "perch": {
    "name": "Perch",
    "wt": 0.25,
    "tint": "range",
    "worth": 2
  },
  "carp": {
    "name": "Carp",
    "wt": 0.35,
    "tint": "range",
    "worth": 3
  },
  "goldenKoi": {
    "name": "Golden Koi",
    "wt": 0.3,
    "tint": "gold",
    "worth": 10
  },
  "moss": {
    "name": "River Moss",
    "wt": 0.05,
    "tint": "plant",
    "worth": 1
  },
  "pebble": {
    "name": "Pebble",
    "wt": 0.1,
    "tint": "stone",
    "worth": 1
  },
  "brookTrout": {
    "name": "Brook Trout",
    "wt": 0.25,
    "tint": "range",
    "worth": 3
  },
  "dace": {
    "name": "Dace",
    "wt": 0.2,
    "tint": "range",
    "worth": 2
  },
  "minnow": {
    "name": "Minnow",
    "wt": 0.1,
    "tint": "range",
    "worth": 1
  },
  "glassEel": {
    "name": "Glass Eel",
    "wt": 0.18,
    "tint": "spirit",
    "worth": 9
  },
  "driftwood": {
    "name": "Driftwood",
    "wt": 0.4,
    "tint": "wood",
    "worth": 1
  },
  "riverKelp": {
    "name": "River Kelp",
    "wt": 0.08,
    "tint": "plant",
    "worth": 2
  },
  "riverTrout": {
    "name": "River Trout",
    "wt": 0.3,
    "tint": "range",
    "worth": 3
  },
  "grayling": {
    "name": "Grayling",
    "wt": 0.25,
    "tint": "range",
    "worth": 3
  },
  "pike": {
    "name": "Pike",
    "wt": 0.45,
    "tint": "range",
    "worth": 4
  },
  "silverSalmon": {
    "name": "Silver Salmon",
    "wt": 0.4,
    "tint": "spirit",
    "worth": 12
  },
  "lakeweed": {
    "name": "Lakeweed",
    "wt": 0.08,
    "tint": "plant",
    "worth": 2
  },
  "freshwaterMussel": {
    "name": "Freshwater Mussel",
    "wt": 0.12,
    "tint": "cloth",
    "worth": 2
  },
  "bass": {
    "name": "Bass",
    "wt": 0.35,
    "tint": "range",
    "worth": 3
  },
  "catfish": {
    "name": "Catfish",
    "wt": 0.45,
    "tint": "range",
    "worth": 4
  },
  "whitefish": {
    "name": "Whitefish",
    "wt": 0.3,
    "tint": "range",
    "worth": 3
  },
  "moonfin": {
    "name": "Moonfin",
    "wt": 0.25,
    "tint": "spirit",
    "worth": 11
  },
  "cookedBluegill": {
    "name": "Cooked Bluegill",
    "wt": 0.25,
    "tint": "ember",
    "worth": 3
  },
  "cookedPerch": {
    "name": "Cooked Perch",
    "wt": 0.25,
    "tint": "ember",
    "worth": 3
  },
  "cookedCarp": {
    "name": "Cooked Carp",
    "wt": 0.28,
    "tint": "ember",
    "worth": 4
  },
  "cookedGoldenKoi": {
    "name": "Cooked Golden Koi",
    "wt": 0.28,
    "tint": "ember",
    "worth": 11
  },
  "cookedBrookTrout": {
    "name": "Cooked Brook Trout",
    "wt": 0.25,
    "tint": "ember",
    "worth": 4
  },
  "cookedDace": {
    "name": "Cooked Dace",
    "wt": 0.22,
    "tint": "ember",
    "worth": 3
  },
  "cookedMinnow": {
    "name": "Cooked Minnow",
    "wt": 0.12,
    "tint": "ember",
    "worth": 2
  },
  "cookedGlassEel": {
    "name": "Cooked Glass Eel",
    "wt": 0.2,
    "tint": "ember",
    "worth": 10
  },
  "cookedRiverTrout": {
    "name": "Cooked River Trout",
    "wt": 0.3,
    "tint": "ember",
    "worth": 4
  },
  "cookedGrayling": {
    "name": "Cooked Grayling",
    "wt": 0.25,
    "tint": "ember",
    "worth": 4
  },
  "cookedPike": {
    "name": "Cooked Pike",
    "wt": 0.4,
    "tint": "ember",
    "worth": 5
  },
  "cookedSilverSalmon": {
    "name": "Cooked Silver Salmon",
    "wt": 0.38,
    "tint": "ember",
    "worth": 13
  },
  "cookedBass": {
    "name": "Cooked Bass",
    "wt": 0.3,
    "tint": "ember",
    "worth": 4
  },
  "cookedCatfish": {
    "name": "Cooked Catfish",
    "wt": 0.4,
    "tint": "ember",
    "worth": 5
  },
  "cookedWhitefish": {
    "name": "Cooked Whitefish",
    "wt": 0.28,
    "tint": "ember",
    "worth": 4
  },
  "cookedMoonfin": {
    "name": "Cooked Moonfin",
    "wt": 0.25,
    "tint": "ember",
    "worth": 12
  }
});

  /* ---- Cards ---- */
  Object.assign(G.CARDS, {
  "strikeStone": {
    "kind": "melee",
    "name": "Stone Sword",
    "type": "Melee",
    "skill": "melee",
    "atk": 2,
    "durability": 12,
    "xp": 10,
    "tint": "blood",
    "tier": 1
  },
  "strikeBronze": {
    "kind": "melee",
    "name": "Bronze Sword",
    "type": "Melee",
    "skill": "melee",
    "atk": 4,
    "durability": 24,
    "xp": 30,
    "tint": "blood",
    "tier": 3
  },
  "shoot": {
    "kind": "ranged",
    "name": "Loose Arrow",
    "type": "Ranged",
    "skill": "archery",
    "atk": 1,
    "durability": 12,
    "tint": "range",
    "xp": 5,
    "tier": 1
  },
  "pickFlint": {
    "kind": "mine",
    "name": "Flint Pick",
    "type": "Tool",
    "skill": "mining",
    "atk": 1,
    "durability": 6,
    "xp": 5,
    "tint": "stone",
    "tier": 0
  },
  "pickStone": {
    "kind": "mine",
    "name": "Stone Pick",
    "type": "Tool",
    "skill": "mining",
    "atk": 2,
    "durability": 12,
    "xp": 10,
    "tint": "stone",
    "tier": 1
  },
  "pickScrap": {
    "kind": "mine",
    "name": "Scrap Pick",
    "type": "Tool",
    "skill": "mining",
    "atk": 4,
    "durability": 18,
    "xp": 20,
    "tint": "stone",
    "tier": 2
  },
  "axeScrap": {
    "kind": "axe",
    "name": "Scrap Axe",
    "type": "Tool",
    "skill": "woodcut",
    "atk": 3,
    "durability": 18,
    "xp": 20,
    "tint": "wood",
    "tier": 2
  },
  "axeFlint": {
    "kind": "axe",
    "name": "Flint Axe",
    "type": "Tool",
    "skill": "woodcut",
    "atk": 1,
    "durability": 6,
    "xp": 5,
    "tint": "wood",
    "tier": 0
  },
  "axeStone": {
    "kind": "axe",
    "name": "Stone Axe",
    "type": "Tool",
    "skill": "woodcut",
    "atk": 2,
    "durability": 12,
    "xp": 10,
    "tint": "wood",
    "tier": 1
  },
  "woodenClub": {
    "kind": "melee",
    "name": "Wooden Club",
    "type": "Melee",
    "skill": "melee",
    "tint": "Blood",
    "atk": 1,
    "durability": 5,
    "xp": 5,
    "tier": 0
  },
  "strikeScrap": {
    "kind": "melee",
    "name": "Scrap Sword",
    "type": "Melee",
    "skill": "melee",
    "atk": 3,
    "durability": 18,
    "xp": 20,
    "tint": "blood",
    "tier": 2
  },
  "fishingNet": {
    "kind": "fishing",
    "name": "Fishing Net",
    "type": "Tool",
    "skill": "fishing",
    "atk": 1,
    "durability": 8,
    "xp": 9,
    "tint": "range",
    "tier": 0
  },
  "fishingRod": {
    "kind": "fishing",
    "name": "Fishing Rod",
    "type": "Tool",
    "skill": "fishing",
    "atk": 2,
    "durability": 14,
    "xp": 11,
    "tint": "range",
    "tier": 1
  }
});

  /* ---- Locations ---- */
  Object.assign(G.LOCATIONS, {
  "boulder": {
    "name": "Boulder",
    "hp": 4,
    "sprite": "boulder",
    "requires": "mine",
    "dropTable": [
      {
        "oneOf": [
          { "key": "stone", "min": 4, "max": 6 },
          { "key": "stone", "min": 4, "max": 6 },
          { "key": "stone", "min": 4, "max": 6 },
          { "key": "basalt", "min": 4, "max": 6 }
        ]
      },
      {
        "key": "flint",
        "chance": 0.25
      },
      {
        "key": "ruby",
        "chance": 0.05
      }
    ]
  },
  "pineTree": {
    "name": "Pine Tree",
    "hp": 4,
    "sprite": "tree",
    "requires": "axe",
    "dropTable": [
      {
        "key": "wood",
        "min": 6,
        "max": 6
      }
    ]
  },
  "oakTree": {
    "name": "Oak Tree",
    "hp": 6,
    "sprite": "wood",
    "requires": "axe",
    "requiresCard": "axeBronze",
    "dropTable": [
      {
        "key": "wood",
        "min": 7,
        "max": 9
      },
      {
        "key": "stick",
        "min": 1,
        "max": 2
      }
    ]
  },
  "fallenOak": {
    "name": "Fallen Oak",
    "hp": 5,
    "sprite": "wood",
    "requires": "axe",
    "requiresCard": "axeBronze",
    "dropTable": [
      {
        "key": "wood",
        "min": 6,
        "max": 8
      }
    ]
  },
  "brushlineOak": {
    "name": "Brushline Oak",
    "hp": 5,
    "sprite": "wood",
    "requires": "axe",
    "requiresCard": "axeBronze",
    "dropTable": [
      {
        "key": "wood",
        "min": 5,
        "max": 7
      },
      {
        "key": "stick",
        "min": 2,
        "max": 3
      }
    ]
  },
  "birchTree": {
    "name": "Birch Tree",
    "hp": 6,
    "sprite": "tree",
    "requires": "axe",
    "requiresCard": "axeBronze",
    "dropTable": [
      {
        "key": "birchLog",
        "min": 5,
        "max": 7
      }
    ]
  },
  "stoneDeposit": {
    "name": "Stone Deposit",
    "hp": 5,
    "sprite": "stone",
    "requires": "mine",
    "dropTable": [
      {
        "key": "stone",
        "min": 5,
        "max": 7
      },
      {
        "key": "coal",
        "chance": 0.2
      }
    ]
  },
  "copperVein": {
    "name": "Copper Vein",
    "hp": 6,
    "sprite": "stone",
    "requires": "mine",
    "requiresCard": "pickScrap",
    "dropTable": [
      {
        "key": "copper",
        "min": 1,
        "max": 2
      },
      {
        "key": "stone",
        "min": 2,
        "max": 3
      },
      {
        "key": "coal",
        "chance": 0.25
      }
    ]
  },
  "tinVein": {
    "name": "Tin Vein",
    "hp": 6,
    "sprite": "stone",
    "requires": "mine",
    "requiresCard": "pickScrap",
    "dropTable": [
      {
        "key": "tin",
        "min": 1,
        "max": 2
      },
      {
        "key": "stone",
        "min": 2,
        "max": 3
      },
      {
        "key": "coal",
        "chance": 0.25
      }
    ]
  },
  "riverbank": {
    "name": "Riverbank",
    "hp": 5,
    "sprite": "river",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "riverTrout"
          },
          {
            "key": "grayling"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "driftwood"
          },
          {
            "key": "moss"
          }
        ]
      },
      {
        "key": "silverSalmon",
        "chance": 0.01
      }
    ]
  },
  "shallowFord": {
    "name": "Shallow Ford",
    "hp": 5,
    "sprite": "river",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "riverTrout"
          },
          {
            "key": "pike"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "riverKelp"
          },
          {
            "key": "pebble"
          }
        ]
      },
      {
        "key": "silverSalmon",
        "chance": 0.012
      }
    ]
  },
  "fishersStep": {
    "name": "Fisher's Step",
    "hp": 6,
    "sprite": "river",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "grayling"
          },
          {
            "key": "pike"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "driftwood"
          },
          {
            "key": "riverKelp"
          }
        ]
      },
      {
        "key": "silverSalmon",
        "chance": 0.015
      }
    ]
  },
  "narrowStream": {
    "name": "Narrow Stream",
    "hp": 5,
    "sprite": "stream",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "brookTrout"
          },
          {
            "key": "dace"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "moss"
          },
          {
            "key": "pebble"
          }
        ]
      },
      {
        "key": "glassEel",
        "chance": 0.012
      }
    ]
  },
  "mossyBank": {
    "name": "Mossy Bank",
    "hp": 5,
    "sprite": "stream",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "brookTrout"
          },
          {
            "key": "minnow"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "moss"
          },
          {
            "key": "driftwood"
          }
        ]
      },
      {
        "key": "glassEel",
        "chance": 0.01
      }
    ]
  },
  "coldRunnel": {
    "name": "Cold Runnel",
    "hp": 6,
    "sprite": "stream",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "dace"
          },
          {
            "key": "minnow"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "pebble"
          },
          {
            "key": "moss"
          }
        ]
      },
      {
        "key": "glassEel",
        "chance": 0.015
      }
    ]
  },
  "pineStand": {
    "name": "Pine Stand",
    "hp": 4,
    "sprite": "wood",
    "requires": "axe",
    "dropTable": [
      {
        "key": "wood",
        "min": 5,
        "max": 7
      }
    ]
  },
  "resinPines": {
    "name": "Resin Pines",
    "hp": 5,
    "sprite": "wood",
    "requires": "axe",
    "dropTable": [
      {
        "key": "wood",
        "min": 4,
        "max": 6
      },
      {
        "key": "stick",
        "min": 2,
        "max": 3
      }
    ]
  },
  "woodYard": {
    "name": "Wood Yard",
    "hp": 4,
    "sprite": "wood",
    "requires": "axe",
    "dropTable": [
      {
        "key": "wood",
        "min": 3,
        "max": 5
      },
      {
        "key": "stick",
        "min": 2,
        "max": 4
      }
    ]
  },
  "grandMarket": {
    "name": "Grand Market",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "key": "gold",
        "min": 2,
        "max": 4
      },
      {
        "oneOf": [
          {
            "key": "berries"
          },
          {
            "key": "cloth"
          }
        ]
      }
    ]
  },
  "tradersRow": {
    "name": "Traders' Row",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "key": "gold",
        "min": 1,
        "max": 3
      },
      {
        "oneOf": [
          {
            "key": "tanningSalt"
          },
          {
            "key": "scrapMetal"
          }
        ]
      }
    ]
  },
  "provisionSquare": {
    "name": "Provision Square",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "cookedPoultry"
          },
          {
            "key": "cookedPork"
          },
          {
            "key": "berries"
          }
        ]
      },
      {
        "key": "gold",
        "min": 1,
        "max": 2,
        "chance": 0.6
      }
    ]
  },
  "riverDock": {
    "name": "River Dock",
    "hp": 5,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "riverTrout"
          },
          {
            "key": "grayling"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "riverKelp"
          },
          {
            "key": "driftwood"
          }
        ]
      }
    ]
  },
  "cargoSlip": {
    "name": "Cargo Slip",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "wood"
          },
          {
            "key": "stick"
          },
          {
            "key": "scrapMetal"
          }
        ]
      },
      {
        "key": "gold",
        "min": 1,
        "max": 3,
        "chance": 0.5
      }
    ]
  },
  "ferryPlatform": {
    "name": "Ferry Platform",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "gold"
          },
          {
            "key": "riverTrout"
          },
          {
            "key": "cloth"
          }
        ]
      }
    ]
  },
  "civicQuarter": {
    "name": "Civic Quarter",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "cloth"
          },
          {
            "key": "flax"
          },
          {
            "key": "gold"
          }
        ]
      }
    ]
  },
  "embassyWalk": {
    "name": "Embassy Walk",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "gold"
          },
          {
            "key": "scrapMetal"
          },
          {
            "key": "berries"
          }
        ]
      }
    ]
  },
  "oldGate": {
    "name": "Old Gate",
    "hp": 4,
    "sprite": "map",
    "requires": "forage",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "stone"
          },
          {
            "key": "coal"
          },
          {
            "key": "gold"
          }
        ]
      }
    ]
  },
  "bridgeRaider": {
    "name": "Bridge Raider",
    "hp": 8,
    "atk": 6,
    "sprite": "goblin",
    "requires": "combat",
    "dropTable": [
      {
        "key": "bone",
        "min": 1,
        "max": 2
      },
      {
        "key": "gold",
        "min": 2,
        "max": 6,
        "chance": 0.7
      },
      {
        "key": "scrapMetal",
        "min": 1,
        "max": 2,
        "chance": 0.6
      }
    ]
  },
  "bridgeSkirmisher": {
    "name": "Bridge Skirmisher",
    "hp": 7,
    "atk": 6,
    "sprite": "goblin",
    "requires": "combat",
    "dropTable": [
      {
        "key": "bone"
      },
      {
        "key": "gold",
        "min": 1,
        "max": 5,
        "chance": 0.65
      },
      {
        "key": "leatherScrap",
        "min": 1,
        "max": 3,
        "chance": 0.5
      }
    ]
  },
  "barricadeBrute": {
    "name": "Barricade Brute",
    "hp": 11,
    "atk": 7,
    "sprite": "goblin",
    "requires": "combat",
    "dropTable": [
      {
        "key": "bone",
        "min": 2,
        "max": 3
      },
      {
        "key": "gold",
        "min": 3,
        "max": 8,
        "chance": 0.75
      },
      {
        "key": "tanningSalt",
        "min": 1,
        "max": 2,
        "chance": 0.55
      },
      {
        "key": "scrapMetal",
        "min": 1,
        "max": 2,
        "chance": 0.5
      }
    ]
  },
  "docks": {
    "name": "Docks",
    "hp": 4,
    "sprite": "map",
    "requires": "mine",
    "dropTable": []
  },
  "pond": {
    "name": "Pond",
    "hp": 4,
    "sprite": "pond",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "bluegill"
          },
          {
            "key": "perch"
          },
          {
            "key": "carp"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "pondweed"
          },
          {
            "key": "smoothStone"
          }
        ]
      },
      {
        "key": "goldenKoi",
        "chance": 0.02
      }
    ]
  },
  "stream": {
    "name": "Stream",
    "hp": 5,
    "sprite": "stream",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "brookTrout"
          },
          {
            "key": "dace"
          },
          {
            "key": "minnow"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "moss"
          },
          {
            "key": "pebble"
          }
        ]
      },
      {
        "key": "glassEel",
        "chance": 0.015
      }
    ]
  },
  "river": {
    "name": "River",
    "hp": 6,
    "sprite": "river",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "riverTrout"
          },
          {
            "key": "grayling"
          },
          {
            "key": "pike"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "driftwood"
          },
          {
            "key": "riverKelp"
          }
        ]
      },
      {
        "key": "silverSalmon",
        "chance": 0.012
      }
    ]
  },
  "lake": {
    "name": "Lake",
    "hp": 7,
    "sprite": "lake",
    "requires": "fishing",
    "dropTable": [
      {
        "oneOf": [
          {
            "key": "bass"
          },
          {
            "key": "catfish"
          },
          {
            "key": "whitefish"
          }
        ]
      },
      {
        "oneOf": [
          {
            "key": "lakeweed"
          },
          {
            "key": "freshwaterMussel"
          }
        ]
      },
      {
        "key": "moonfin",
        "chance": 0.01
      }
    ]
  }
});

  /* ---- Zones ---- */
  Object.assign(G.ZONES, {
  "kharBarak": {
    "name": "Khar-Barak",
    "kind": "City",
    "region": "khar",
    "order": 3,
    "bank": true,
    "blurb": "The first trade city of the marches. Ore, river, and pine all feed the furnaces below the gate.",
    "deck": {
      "flint": 8,
      "stick": 6
    },
    "slotLabels": [
      "Mines",
      "River",
      "Timber"
    ],
    "locationDecks": [
      {
        "stoneDeposit": 4,
        "copperVein": 4,
        "tinVein": 4
      },
      {
        "riverbank": 3,
        "shallowFord": 3,
        "fishersStep": 2
      },
      {
        "pineStand": 4,
        "resinPines": 3,
        "woodYard": 3
      }
    ],
    "lootPool": [
      "tin",
      "tin",
      "copper",
      "copper",
      "coal",
      "coal",
      "bronzeBar",
      "bronzeBar",
      "gold",
      "gold",
      "diamond",
      "ruby",
      "emerald"
    ],
    "foilPool": [
      "flint",
      "stick",
      "fishingRod"
    ],
    "cape": "gatebreakerCape",
    "needs": {
      "kills": 20
    }
  },
  "stillTidePass": {
    "name": "Still-tide Pass",
    "kind": "Wilds",
    "region": "leth-eiren",
    "order": 3,
    "blurb": "A cold pass of oak growth and fast water. Goblins stalk the bends while deer pick through the verge.",
    "deck": {
      "flint": 6,
      "stick": 6,
      "forage": 8
    },
    "slotLabels": [
      "Stream",
      "Oakwood",
      "Pass"
    ],
    "locationDecks": [
      {
        "narrowStream": 3,
        "mossyBank": 3,
        "coldRunnel": 2
      },
      {
        "oakTree": 4,
        "fallenOak": 3,
        "brushlineOak": 3,
        "birchTree": 2
      },
      {
        "goblin": 4,
        "deer": 3,
        "pig": 2,
        "chicken": 1
      }
    ],
    "lootPool": [
      "wood",
      "wood",
      "wood",
      "stick",
      "stick",
      "brookTrout",
      "dace",
      "bone",
      "bone",
      "hide",
      "scrapMetal",
      "gold"
    ],
    "foilPool": [
      "axeFlint",
      "axeStone",
      "shoot",
      "fishingRod"
    ],
    "cape": "roadwardenCape",
    "needs": {
      "kills": 25
    }
  },
  "duunVaelBridge": {
    "name": "Duun-Vael Bridge",
    "kind": "Gauntlet",
    "region": "leth-eiren",
    "order": 4,
    "blurb": "A narrow crossing choked with raiders and splintered barricades. The only way forward is through.",
    "deck": {
      "strikeStone": 6,
      "woodenClub": 6,
      "shoot": 4,
      "forage": 2
    },
    "slotLabels": [
      "Bridge",
      "Approach",
      "Barricade"
    ],
    "locationDecks": [
      {
        "bridgeRaider": 5,
        "bridgeSkirmisher": 3
      },
      {
        "bridgeSkirmisher": 5,
        "goblin": 3
      },
      {
        "barricadeBrute": 4,
        "bridgeRaider": 3
      }
    ],
    "lootPool": [
      "bone",
      "bone",
      "bone",
      "gold",
      "gold",
      "scrapMetal",
      "scrapMetal",
      "leatherScrap",
      "tanningSalt",
      "coal"
    ],
    "foilPool": [
      "woodenClub",
      "strikeStone",
      "strikeBronze",
      "shoot"
    ],
    "cape": "gatebreakerCape",
    "needs": {
      "kills": 45
    }
  },
  "riverhold": {
    "name": "Riverhold",
    "kind": "City",
    "region": "keth-maral",
    "order": 1,
    "bank": true,
    "factions": [
      "ashkar",
      "delborn",
      "emberkin",
      "riverborn"
    ],
    "blurb": "The first great city beyond the marches. Markets, docks, and faction halls all pull at your loyalty.",
    "deck": {
      "forage": 10,
      "stick": 4,
      "flint": 4
    },
    "slotLabels": [
      "Market",
      "Docks",
      "Ward"
    ],
    "locationDecks": [
      {
        "grandMarket": 3,
        "tradersRow": 3,
        "provisionSquare": 2
      },
      {
        "riverDock": 3,
        "cargoSlip": 3,
        "ferryPlatform": 2
      },
      {
        "civicQuarter": 3,
        "embassyWalk": 3,
        "oldGate": 2
      }
    ],
    "lootPool": [
      "gold",
      "gold",
      "gold",
      "cloth",
      "berries",
      "riverTrout",
      "grayling",
      "scrapMetal",
      "tanningSalt",
      "diamond",
      "ruby",
      "emerald"
    ],
    "foilPool": [
      "forage",
      "stick",
      "fishingRod"
    ],
    "cape": "gatebreakerCape",
    "needs": {
      "kills": 45
    }
  }
});

  /* ---- Skills ---- */
  Object.assign(G.SKILLS, {
  "woodcut": {
    "name": "Logging",
    "tint": "wood",
    "need": 24,
    "perks": {
      "3": "Logs yield +1",
      "5": "Logs yield +1"
    }
  },
  "tailor": {
    "name": "Tailor",
    "tint": "stone",
    "need": 24,
    "perks": {
      "5": "Double String Production",
      "25": "Double String Production"
    }
  },
  "fishing": {
    "name": "Fishing",
    "tint": "range",
    "need": 26,
    "perks": {
      "3": "Steadier casts",
      "6": "Better reads on the water",
      "10": "Journal fills fast"
    }
  }
});

  /* ---- Tuning ---- */
  Object.assign(G.TUNE, {
  "bandMin": 0.1,
  "bandMax": 0.25,
  "harvestBandPerLv": 0.025,
  "farmPlotsBase": 3
});

  /* ---- Crafting stations ---- */
  (function () {
    var UPSERT = [
  {
    "id": "hands",
    "name": "Bare Hands",
    "sub": "Flint tools — crude, but need nothing built",
    "buildCost": {},
    "recipes": [
      {
        "id": "flintPick",
        "name": "Flint Pick",
        "cost": {
          "flint": 6,
          "stick": 6
        },
        "repeatable": true,
        "grantsCard": "pickFlint",
        "effect": "adds a Swing Pick card — crude, wears fast"
      },
      {
        "id": "flintAxe",
        "name": "Flint Axe",
        "cost": {
          "flint": 6,
          "stick": 6
        },
        "repeatable": true,
        "grantsCard": "axeFlint",
        "effect": "adds a Fell Tree card — crude, wears fast"
      },
      {
        "id": "woodenClub",
        "name": "Wooden Club",
        "cost": {
          "flint": 4,
          "stick": 4
        },
        "effect": "Adds Wooden Club Card - Crude ",
        "repeatable": true,
        "grantsCard": "woodenClub",
        "skill": "crafting",
        "xp": 1
      }
    ],
    "upgrades": []
  },
  {
    "id": "bench",
    "name": "Crafting Bench",
    "sub": "Basic tools and fittings",
    "buildCost": {
      "basaltBlock": 2,
      "planks": 12
    },
    "villagerHireCost": {
      "planks": 15,
      "stick": 10
    },
    "alwaysShown": true,
    "upgrades": [
      {
        "cost": {
          "basaltBlock": 8,
          "planks": 30
        },
        "speedMult": 0.65
      }
    ],
    "recipes": [
      {
        "id": "axe",
        "name": "Stone Axe",
        "cost": {
          "stoneBlock": 1,
          "planks": 6
        },
        "repeatable": true,
        "zones": [
          "aerendell"
        ],
        "grantsCard": "axeStone",
        "effect": "adds a Fell Tree card"
      },
      {
        "id": "scrapAxe",
        "name": "Scrap Axe",
        "cost": {
          "scrapMetal": 4,
          "planks": 6
        },
        "repeatable": true,
        "zones": [
          "forestRoad",
          "kharBarak"
        ],
        "grantsCard": "axeScrap",
        "effect": "adds a Fell Tree card — sturdier than stone"
      },
      {
        "id": "stonePick",
        "name": "Stone Pick",
        "cost": {
          "planks": 6,
          "stoneBlock": 1
        },
        "repeatable": true,
        "zones": [
          "aerendell"
        ],
        "grantsCard": "pickStone",
        "effect": "adds a Swing Pick card"
      },
      {
        "id": "scrapPick",
        "name": "Scrap Pick",
        "cost": {
          "scrapMetal": 4,
          "stick": 6
        },
        "repeatable": true,
        "zones": [
          "forestRoad",
          "kharBarak"
        ],
        "grantsCard": "pickScrap",
        "effect": "adds a Swing Pick card — the only way to work ore"
      },
      {
        "id": "stoneSword",
        "name": "Stone Sword",
        "cost": {
          "stoneBlock": 1,
          "planks": 4
        },
        "repeatable": true,
        "zones": [
          "aerendell"
        ],
        "grantsCard": "strikeStone",
        "effect": "adds a Strike card"
      },
      {
        "id": "scrapSword",
        "name": "Scrap Sword",
        "cost": {
          "scrapMetal": 4,
          "planks": 4
        },
        "repeatable": true,
        "zones": [
          "forestRoad",
          "kharBarak"
        ],
        "grantsCard": "strikeScrap",
        "effect": "adds a Strike card — sturdier than stone"
      },
      {
        "id": "shortBow",
        "name": "Short Bow",
        "cost": {
          "planks": 5,
          "string": 2
        },
        "repeatable": true,
        "grantsCard": "shoot",
        "effect": "adds a Loose Arrow card"
      },
      {
        "id": "scrapLeather",
        "name": "Stitch Leather",
        "cost": {
          "leatherScrap": 3
        },
        "villagerRecipe": true,
        "repeatable": true,
        "gives": {
          "leather": 1
        },
        "skill": "crafting",
        "xp": 6,
        "effect": "three scraps make one leather"
      },
      {
        "id": "backpack",
        "name": "Backpack",
        "cost": {
          "stick": 8,
          "planks": 4,
          "cloth": 2
        },
        "equips": "backpack",
        "effect": "+10 carry capacity"
      },
      {
        "id": "woolPack",
        "name": "Wool Pack",
        "cost": {
          "planks": 14,
          "stone": 6
        },
        "equips": "woolPack",
        "effect": "+14 carry capacity"
      },
      {
        "id": "fishingNet",
        "name": "Fishing Net",
        "cost": {
          "stick": 8,
          "flax": 6
        },
        "repeatable": true,
        "zones": [
          "forestRoad"
        ],
        "grantsCard": "fishingNet",
        "skill": "crafting",
        "xp": 6,
        "effect": "adds a Fishing Net card for fishing holes"
      },
      {
        "id": "fishingRod",
        "name": "Fishing Rod",
        "cost": {
          "birchPlanks": 4,
          "string": 2,
          "bone": 2
        },
        "repeatable": true,
        "zones": [
          "forestRoad",
          "stillTidePass",
          "kharBarak",
          "duunVaelBridge",
          "riverhold"
        ],
        "grantsCard": "fishingRod",
        "skill": "crafting",
        "xp": 8,
        "effect": "adds a stronger fishing card — needs Birch Planks"
      }
    ]
  },
  {
    "id": "loom",
    "name": "Loom",
    "sub": "Weave string into cloth",
    "buildCost": {
      "planks": 10,
      "stick": 14
    },
    "villagerHireCost": {
      "planks": 10,
      "stick": 10
    },
    "zones": [
      "aerendell",
      "forestRoad"
    ],
    "upgrades": [
      {
        "cost": {
          "planks": 20,
          "cloth": 10
        },
        "speedMult": 0.65
      }
    ],
    "recipes": [
      {
        "id": "cloth",
        "name": "Weave Cloth",
        "cost": {
          "string": 4
        },
        "repeatable": true,
        "gives": {
          "cloth": 1
        },
        "skill": "crafting",
        "xp": 8,
        "effect": "four string makes one cloth"
      },
      {
        "id": "highlandCloth",
        "name": "Spin Highland Cloth",
        "cost": {
          "highlandWool": 4
        },
        "repeatable": true,
        "gives": {
          "highlandCloth": 1
        },
        "skill": "crafting",
        "xp": 8,
        "effect": "four highland wool spun into one cloth"
      },
      {
        "id": "string",
        "name": "String",
        "cost": {
          "flax": 3
        },
        "villagerRecipe": true,
        "effect": "",
        "repeatable": true,
        "gives": {
          "string": 1
        },
        "skill": "crafting",
        "xp": 1
      }
    ]
  },
  {
    "id": "altar",
    "name": "Bone Altar",
    "sub": "Prayer — bury bones for points",
    "buildCost": {
      "basaltBlock": 6,
      "bone": 5
    },
    "villagerHireCost": {
      "basaltBlock": 5,
      "bone": 10
    },
    "upgrades": [
      {
        "cost": {
          "basaltBlock": 12,
          "bone": 12
        },
        "speedMult": 0.65
      }
    ],
    "recipes": [
      {
        "id": "buryBone",
        "name": "Bury Bone",
        "cost": {
          "bone": 1
        },
        "villagerRecipe": true,
        "repeatable": true,
        "prayer": 1,
        "effect": "earns prayer points and prayer xp"
      }
    ]
  },
  {
    "id": "firepit",
    "name": "Campfire",
    "sub": "Cook food, burn planks to charcoal",
    "page": "farm",
    "buildCost": {
      "stick": 12,
      "flint": 8
    },
    "villagerHireCost": {
      "stick": 15,
      "flint": 10
    },
    "upgrades": [
      {
        "cost": {
          "planks": 25,
          "stick": 20
        },
        "speedMult": 0.65
      }
    ],
    "recipes": [
      {
        "id": "cookPoultry",
        "name": "Cook Poultry",
        "cost": {
          "poultry": 1,
          "stick": 1
        },
        "repeatable": true,
        "gives": {
          "cookedPoultry": 1
        },
        "skill": "cooking",
        "xp": 8,
        "effect": "turns raw poultry into food"
      },
      {
        "id": "makeCharcoal",
        "name": "Burn Charcoal",
        "cost": {
          "planks": 1,
          "stick": 1
        },
        "villagerRecipe": true,
        "repeatable": true,
        "gives": {
          "charcoal": 1
        },
        "skill": "cooking",
        "xp": 6,
        "effect": "burns planks down to charcoal"
      },
      {
        "id": "cookSteak",
        "name": "Cook Steak",
        "cost": {
          "steak": 1,
          "stick": 1
        },
        "repeatable": true,
        "gives": {
          "cookedSteak": 1
        },
        "skill": "cooking",
        "xp": 12,
        "effect": "turns raw steak into food"
      },
      {
        "id": "cookPork",
        "name": "Cook Pork",
        "cost": {
          "pork": 1,
          "stick": 1
        },
        "repeatable": true,
        "gives": {
          "cookedPork": 1
        },
        "skill": "cooking",
        "xp": 10,
        "effect": "turns raw pork into food"
      },
      {
        "id": "cook_bluegill",
        "name": "Cook Bluegill",
        "cost": {
          "stick": 1,
          "bluegill": 1
        },
        "repeatable": true,
        "gives": {
          "cookedBluegill": 1
        },
        "skill": "cooking",
        "xp": 8,
        "effect": "cooks bluegill into food"
      },
      {
        "id": "cook_perch",
        "name": "Cook Perch",
        "cost": {
          "stick": 1,
          "perch": 1
        },
        "repeatable": true,
        "gives": {
          "cookedPerch": 1
        },
        "skill": "cooking",
        "xp": 8,
        "effect": "cooks perch into food"
      },
      {
        "id": "cook_carp",
        "name": "Cook Carp",
        "cost": {
          "stick": 1,
          "carp": 1
        },
        "repeatable": true,
        "gives": {
          "cookedCarp": 1
        },
        "skill": "cooking",
        "xp": 9,
        "effect": "cooks carp into food"
      },
      {
        "id": "cook_goldenKoi",
        "name": "Cook Golden Koi",
        "cost": {
          "stick": 1,
          "goldenKoi": 1
        },
        "repeatable": true,
        "gives": {
          "cookedGoldenKoi": 1
        },
        "skill": "cooking",
        "xp": 14,
        "effect": "cooks golden koi into food"
      },
      {
        "id": "cook_brookTrout",
        "name": "Cook Brook Trout",
        "cost": {
          "stick": 1,
          "brookTrout": 1
        },
        "repeatable": true,
        "gives": {
          "cookedBrookTrout": 1
        },
        "skill": "cooking",
        "xp": 9,
        "effect": "cooks brook trout into food"
      },
      {
        "id": "cook_dace",
        "name": "Cook Dace",
        "cost": {
          "stick": 1,
          "dace": 1
        },
        "repeatable": true,
        "gives": {
          "cookedDace": 1
        },
        "skill": "cooking",
        "xp": 8,
        "effect": "cooks dace into food"
      },
      {
        "id": "cook_minnow",
        "name": "Cook Minnow",
        "cost": {
          "stick": 1,
          "minnow": 1
        },
        "repeatable": true,
        "gives": {
          "cookedMinnow": 1
        },
        "skill": "cooking",
        "xp": 7,
        "effect": "cooks minnow into food"
      },
      {
        "id": "cook_glassEel",
        "name": "Cook Glass Eel",
        "cost": {
          "stick": 1,
          "glassEel": 1
        },
        "repeatable": true,
        "gives": {
          "cookedGlassEel": 1
        },
        "skill": "cooking",
        "xp": 14,
        "effect": "cooks glass eel into food"
      },
      {
        "id": "cook_riverTrout",
        "name": "Cook River Trout",
        "cost": {
          "stick": 1,
          "riverTrout": 1
        },
        "repeatable": true,
        "gives": {
          "cookedRiverTrout": 1
        },
        "skill": "cooking",
        "xp": 9,
        "effect": "cooks river trout into food"
      },
      {
        "id": "cook_grayling",
        "name": "Cook Grayling",
        "cost": {
          "stick": 1,
          "grayling": 1
        },
        "repeatable": true,
        "gives": {
          "cookedGrayling": 1
        },
        "skill": "cooking",
        "xp": 9,
        "effect": "cooks grayling into food"
      },
      {
        "id": "cook_pike",
        "name": "Cook Pike",
        "cost": {
          "stick": 1,
          "pike": 1
        },
        "repeatable": true,
        "gives": {
          "cookedPike": 1
        },
        "skill": "cooking",
        "xp": 11,
        "effect": "cooks pike into food"
      },
      {
        "id": "cook_silverSalmon",
        "name": "Cook Silver Salmon",
        "cost": {
          "stick": 1,
          "silverSalmon": 1
        },
        "repeatable": true,
        "gives": {
          "cookedSilverSalmon": 1
        },
        "skill": "cooking",
        "xp": 16,
        "effect": "cooks silver salmon into food"
      },
      {
        "id": "cook_bass",
        "name": "Cook Bass",
        "cost": {
          "stick": 1,
          "bass": 1
        },
        "repeatable": true,
        "gives": {
          "cookedBass": 1
        },
        "skill": "cooking",
        "xp": 9,
        "effect": "cooks bass into food"
      },
      {
        "id": "cook_catfish",
        "name": "Cook Catfish",
        "cost": {
          "stick": 1,
          "catfish": 1
        },
        "repeatable": true,
        "gives": {
          "cookedCatfish": 1
        },
        "skill": "cooking",
        "xp": 11,
        "effect": "cooks catfish into food"
      },
      {
        "id": "cook_whitefish",
        "name": "Cook Whitefish",
        "cost": {
          "stick": 1,
          "whitefish": 1
        },
        "repeatable": true,
        "gives": {
          "cookedWhitefish": 1
        },
        "skill": "cooking",
        "xp": 9,
        "effect": "cooks whitefish into food"
      },
      {
        "id": "cook_moonfin",
        "name": "Cook Moonfin",
        "cost": {
          "stick": 1,
          "moonfin": 1
        },
        "repeatable": true,
        "gives": {
          "cookedMoonfin": 1
        },
        "skill": "cooking",
        "xp": 16,
        "effect": "cooks moonfin into food"
      }
    ]
  }
];
    UPSERT.forEach(function (st) {
      var i = G.STATIONS.findIndex(function (s) { return s.id === st.id; });
      if (i >= 0) G.STATIONS[i] = st; else G.STATIONS.push(st);
    });
  })();
})(window.Game = window.Game || {});
