/* =========================================================
   custom-sprites.js — GENERATED by tools/editor. Do not hand-edit;
   your changes will be overwritten the next time you click Save
   in the content editor. Loads after sprites.js, so it can add
   new emblems to G.SPRITES and point resource/card/item keys at
   them through G.ALIAS.
   ========================================================= */
(function (G) {
  'use strict';

  // nothing customized yet — use the editor to add content
})(window.Game = window.Game || {});
