/* =========================================================
   custom-assets.js — GENERATED by tools/editor. Do not hand-edit;
   your changes will be overwritten the next time you click Save
   in the content editor. Loads after assets.js, so it can attach
   audio hooks and sprite image overrides without touching base data.
   ========================================================= */
(function (G) {
  'use strict';

  // nothing customized yet — use the editor to add media overrides
})(window.Game = window.Game || {});
